# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentor_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
