# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20161224_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articals',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='artical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.Articals'),
            preserve_default=False,
        ),
    ]
